### ISSUE TITLE
Cluster restore question.

### ISSUE THREAD

**Issue by vnazarenko** [DeviaVir/cassandras3#16]
Should i backup each node in cluster ( because is work with local data folder ) or tool will request data from other nodes automatically - so i could make backup from one cluster node.

**Comment by DeviaVir** [comment]
I think the answer is yes, each node will need to be backed up separately, since there's no single control entity, and this tool doesn't support the gossip protocol.

**Comment by vnazarenko** [comment]
Thank you!
