### ISSUE TITLE
Error restoring data

### ISSUE THREAD

**Issue by jdelk** [DeviaVir/cassandras3#6]
Running Cassandra 3.11.2

The command I'm using is: cassandras3 restore --hostname HostName --backup timestamp --keyspace example_keyspace --bucket test

When I try to restore data I get this error:

IOError: [Errno 2] No such file or directory: u'/var/lib/cassandra/data/example_keyspace/example_table-4389976056ff11e88cba454951819c3a/manifest.json.1D8E9e5a'

It's also not inserting data into the keyspace folder, but creating a folder for example_table-4389976056ff11e88cba454951819c3a directly in /var/lib/cassandra/data

How can I get this to work?

**Comment by jmanuelortizn** [comment]
Same issue Is happening to me.
It looking for a manifest.json.#uuid# which doesn't exists on the S3 snapshot.
